services:
  # 1. Database Container
  postgres:
    image: postgres:15-alpine
    container_name: GitGud_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - GitGud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. NestJS Backend Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: GitGud_backend
    user: "${UID}:${GID}"
    ports:
      - "${API_PORT}:4000"
    environment:
      - PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - GitGud_network

  # 3. NextJS Frontend Container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: GitGud_frontend
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - GitGud_network

volumes:
  pgdata:

networks:
  GitGud_network:
    driver: bridge
